#!/bin/bash
mpirun=/netfs/inf/trahay_f/mpich/bin/mpirun
script=$1
distance=$2
dna=$3

#patterns :
small="AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAA"
medium="AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAA"
large="AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAA"
five_medium="'AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAA AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAG AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAT AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAGG AGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAAAAAGTTTTTTTTTTTTTTTTTTGGAAAAAAAATT'"
patterns=($small $medium $large);

for i in {1..260}; do 
    echo $i MPI process
    for pattern in ${patterns[*]}; do
        echo $pattern
        $mpirun -np $i --hostfile ~/hosts $script $distance $dna $pattern | grep "APM done in" | awk '{ printf $4 }' >> out_mpi
        printf "\t" >> out_mpi
    done
    printf "\n" >> out_mpi

done
